"""Shared constants for the AgentScope AliyunCS CLI example."""

FRAMEWORK_NAME = "agentscope-aliyuncs-cli"

BASE_URL_ENV = "AGENTSCOPE_CLI_BASE_URL"
API_KEY_ENV = "AGENTSCOPE_CLI_API_KEY"
MODEL_ENV = "AGENTSCOPE_CLI_MODEL"
PROTOCOL_ENV = "AGENTSCOPE_CLI_PROTOCOL"
SYSTEM_PROMPT_ENV = "AGENTSCOPE_CLI_SYSTEM_PROMPT"
LOAD_DOTENV_ENV = "AGENTSCOPE_CLI_LOAD_DOTENV"

DEFAULT_SYSTEM_PROMPT = "You are a concise and helpful assistant."
